name: Auto Cherry Pick

on:
  pull_request:
    types:
      - labeled
      - closed

jobs:
  auto-cherry-pick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Auto Cherry Pick
        uses: ./
